apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  ports:
  - name: mysql
    port: 3306
    nodePort: 3307
  selector:
    name: mysql-master
  type: NodePort
