apiVersion: v1
kind: Pod
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  nodeName: k8s-master
  containers:
  - name: mysql-master
    image: 10.100.1.31/library/mysql-master:5.7.21
    ports:
    - containerPort: 3306
      hostPort: 1026
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "bangsun"
    - name: MYSQL_REPLICATION_USER
      value: "jaychiu"
    - name: MYSQL_REPLICATION_PASSWORD
      value: "bangsun"
