apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  replicas: 1
  selector:
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      containers:
      - name: mysql-master
        image: 10.100.1.31/library/mysql-master:0.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "bangsun"
        - name: MYSQL_REPLICATION_USER
          value: "jaychiu"
        - name: MYSQL_REPLICATION_PASSWORD
          value: "bangsun"
